# Generated by Django 6.0.1 on 2026-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
