# Generated by Django 6.0.1 on 2026-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_report_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='completed_reports/'),
        ),
    ]
