# Generated by Django 5.2.13 on 2026-05-09 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_garbagebin_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagebin',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Fill level percentage (1-100)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='garbagebin',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='garbagebin',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
